add tests for rdf:JSON xsd:float and xsd:double
w3c/rdf-tests pull request #152
Opened 2024-11-20 20:28 UTC by pfps

Tests for rounding of numbers and treatment of large numbers.  

Tests for difference between positive and negative zero.

Tests for order dependence of rdf:JSON arrays and order independence of rdf:JSON objects.

2024-11-20 22:56 UTC, gkellogg requested changes
They look basically correct, but there are some syntax errors and places where you may be using the wrong datatype.

2024-11-20 22:56 UTC, gkellogg commented on rdf/rdf12/rdf-semantics/json-array-1.ttl
> +:a :b "[ -0, 0 ]"^^xsd:double
Should this be `:b "[ -0, 0 ]"^^rdf:JSON`?

2024-11-20 22:56 UTC, gkellogg commented on rdf/rdf12/rdf-semantics/json-array-1.ttl
> +:a :b "[ -0, 0 ]"^^xsd:double
```suggestion
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX : <http://example.com/ns#>

:a :b "[ -0, 0 ]"^^rdf:JSON .
```

2024-11-20 22:56 UTC, gkellogg commented on rdf/rdf12/rdf-semantics/json-array-2.ttl
> +:a :b "[ 0, -0 ]"^^xsd:double
```suggestion
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX : <http://example.com/ns#>

:a :b "[ 0, -0 ]"^^rdf:JSON .
```

2024-11-20 22:56 UTC, gkellogg commented on rdf/rdf12/rdf-semantics/json-positive-zero-array.ttl
> +:a :b "[ 0 ]"^^xsd:double
```suggestion
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX : <http://example.com/ns#>

:a :b "[ 0 ]"^^rdf:JSON .
```

2024-11-20 22:57 UTC, pfps commented on rdf/rdf12/rdf-semantics/json-array-1.ttl
> +:a :b "[ -0, 0 ]"^^xsd:double
Yes

2024-11-20 22:59 UTC, pfps commented on rdf/rdf12/rdf-semantics/json-array-1.ttl
> +:a :b "[ -0, 0 ]"^^xsd:double
I think the order shouldn't change.

2024-11-21 09:03 UTC, afs commented on rdf/rdf12/rdf-semantics/manifest.ttl
> +  mf:recognizedDatatypes (rdf:JSON);
`mf:recognizedDatatypes` needs to go into `/ns/test-manifest.ttl`.

That in turn changes the meaning of passing a test.

2024-11-21 09:03 UTC, afs commented on rdf/rdf12/rdf-semantics/manifest.ttl
> +  mf:entailmentRegime "RDF";
`mf:entailmentRegime` needs to in `/ns/test-manifest.ttl`.

2024-11-21 09:03 UTC, afs commented on rdf/rdf12/rdf-semantics/manifest.ttl
> +  mf:unrecognizedDatatypes ();
`mf:unrecognizedDatatypes` needs to go into `/ns/test-manifest.ttl`.

2024-11-21 09:03 UTC, afs commented on rdf/rdf12/rdf-semantics/manifest.ttl
> +
Excess blank line.

2024-11-21 09:03 UTC, afs commented on rdf/rdf12/rdf-semantics/manifest.ttl
`/ns/test-manifest.ttl` needs updating. I've picked out some terms that need to be defined - there may be others.

2024-11-21 19:59 UTC, pfps commented on rdf/rdf12/rdf-semantics/manifest.ttl
> +  mf:unrecognizedDatatypes ();
These IRIs have been in the semantics tests since at least 1.1.  I wonder how the 1.1 testing was done.

2024-11-21 20:03 UTC, pfps commented on rdf/rdf12/rdf-semantics/manifest.ttl
> +
How do I remove a line here?

2024-11-21 20:04 UTC, gkellogg commented on rdf/rdf12/rdf-semantics/manifest.ttl
> +
```suggestion
```

2024-11-21 20:05 UTC, gkellogg approved these changes

2024-11-21 20:06 UTC, gkellogg commented on rdf/rdf12/rdf-semantics/manifest.ttl
> +  mf:unrecognizedDatatypes ();
Test runners don't often actually require the vocabulary terms to be defined, but it is good form to define all the terms used in tests, and pretty much everywhere else.

2024-11-21 20:06 UTC, pfps commented
Is all OK except for the blank line?

#153 has been opened for the IRIs missing in test-manifest.ttl

2024-11-22 09:22 UTC, afs commented on rdf/rdf12/rdf-semantics/manifest.ttl
> +
To keep it as one commit to be merged:

* If changes have been made via teh github UI, "git pull" to you local copy of the branch.
* Edit file.
* git commit

Bonus points for doing a "squash and merge" to turn it into one commit going onto to `main`.

2024-11-22 15:11 UTC, gkellogg commented on rdf/rdf12/rdf-semantics/manifest.ttl
> +
You can also add multiple suggestions into a batch in the UI which will create just one commit. This is done from the "Files changed" view and you'll see a button to "add to batch".

2024-11-23 15:30 UTC, afs approved these changes

2024-12-02 00:05 UTC, merged